src/main/java/jp/ossc/nimbus/servlet/SharedContextServlet.java
=> keyset画面のRemoveボタンのカラムが崩れる不具合を修正した

src/main/java/jp/ossc/nimbus/beans/dataset/RecordList.java
=> RandomAccessをimplementsしました

src/main/java/jp/ossc/nimbus/service/beancontrol/BeanFlowInvokerAccessImpl2.java, src/main/java/jp/ossc/nimbus/service/io/NimbusExternalizerService.java, src/main/java/jp/ossc/nimbus/service/io/SerializableExternalizerService.java, src/main/java/jp/ossc/nimbus/service/io/SerializableExternalizerServiceMBean.java
for要素で、同様の改修をしていたようなので、whileも同様に修正しました。
マージして下さい。
=> BeanFlowのWhile文のContinue、Breakの動きがおかしい #8

pom.xml
@m-takata 
設定を変更したのでマージをお願いします。
=> maven-compiler-pluginの設定を全ソースリコンパイルされないように変更

src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/AuthenticateInterceptorService.java
=> AuthenticateInterceptorServiceでThreadContextに認証情報が設定されない不具合を修正

pom.xml
maven-Javadoc-pluginの設定を修正しましたので、マージをお願いします。
=> Java8でのJavadoc作成時のエラーを無視するように修正した

src/main/java/jp/ossc/nimbus/service/io/NimbusExternalizerService.java
=> Classオブジェクトを直列化/非直列化できるように修正した。

src/main/java/jp/ossc/nimbus/service/scheduler2/DatabaseScheduleManagerService.java, src/main/java/jp/ossc/nimbus/servlet/ScheduleManagerServlet.java
スケジュール、スケジュールマスタの画面をそれぞれ独立させて、画面をシンプルにしました。
また、ステータス変更等のアクション後も検索条件を保持したまま、一覧を再表示するように修正しました。
確認してマージお願いします。ワン。Uo･ｪ･oU
=> 画面構成の見直し、ボタン操作後の検索条件を保持するように修正した

src/main/java/jp/ossc/nimbus/service/publish/local/ClientConnectionImpl.java, src/main/java/jp/ossc/nimbus/service/publish/local/ConnectionFactoryService.java, src/main/java/jp/ossc/nimbus/service/publish/local/ConnectionFactoryServiceMBean.java, src/main/java/jp/ossc/nimbus/service/publish/local/MessageImpl.java, src/main/java/jp/ossc/nimbus/service/publish/local/ServerConnectionImpl.java
ローカルで送受信するPublisherを新規追加したので、マージしてください。
=> ローカルで送受信するPublisherを新規追加

src/main/java/jp/ossc/nimbus/service/writer/publish/ClientConnectionWriterService.java, src/main/java/jp/ossc/nimbus/service/writer/publish/ClientConnectionWriterServiceMBean.java, src/main/java/jp/ossc/nimbus/service/writer/publish/ServerConnectionWriterService.java, src/main/java/jp/ossc/nimbus/service/writer/publish/ServerConnectionWriterServiceMBean.java
以下の機能追加を行ったので、マージしてください。
・ServerConnectionを使って送信するMessageWriter実装サービスを新規追加した。
・ClientConnectionを使って受信してMessageWriterサービスに書き込み依頼するサービスを新規追加した。
=> Publisherを経由して、リモートのMessageWriterサービスに書き込むMessageWriterサービスを追加

pom.xml, src/main/java/jp/ossc/nimbus/beans/ConcatenatedProperty.java, src/main/java/jp/ossc/nimbus/beans/IndexedProperty.java, src/main/java/jp/ossc/nimbus/beans/ListEditor.java, src/main/java/jp/ossc/nimbus/beans/MapEditor.java, src/main/java/jp/ossc/nimbus/beans/MappedProperty.java, src/main/java/jp/ossc/nimbus/beans/NestedProperty.java, src/main/java/jp/ossc/nimbus/beans/NimbusPropertyEditorManager.java, src/main/java/jp/ossc/nimbus/beans/OrProperty.java, src/main/java/jp/ossc/nimbus/beans/ParameterizedTypePropertyEditor.java, src/main/java/jp/ossc/nimbus/beans/ParameterizedTypePropertyEditorSupport.java, src/main/java/jp/ossc/nimbus/beans/Property.java, src/main/java/jp/ossc/nimbus/beans/SimpleProperty.java, src/main/java/jp/ossc/nimbus/beans/SortedMapEditor.java, src/main/java/jp/ossc/nimbus/core/DefaultServiceManagerService.java, src/main/java/jp/ossc/nimbus/service/rest/BeanFlowRestServerService.java, src/main/java/jp/ossc/nimbus/util/converter/BeanJSONConverter.java
=> Genericsに対応した。

src/main/java/jp/ossc/nimbus/service/test/evaluate/BinaryCompareEvaluateActionService.java, src/main/java/jp/ossc/nimbus/service/test/evaluate/BinaryCompareEvaluateActionServiceMBean.java
=> バイナリファイル比較アクションを作成しました。

src/main/java/jp/ossc/nimbus/service/test/action/HttpRequestActionService.java
=> RESTHttpRequestに対して、テストリソース内で、URLキーを指定して、setKey()できるようにした。

src/main/java/jp/ossc/nimbus/service/test/action/JMSMessageSendActionService.java, src/main/java/jp/ossc/nimbus/service/test/action/JMSMessageSendActionServiceMBean.java, src/main/java/jp/ossc/nimbus/service/test/action/ServerConnectionSendActionService.java
=> JMSでMessageを送信するTestActionサービスを追加した。

src/main/java/jp/ossc/nimbus/util/converter/DataSetServletRequestParameterConverter.java
マージしてください。
DataSetServletRequestParameterConverterでmultipartリクエストをサポートした。
=> multipartリクエストをサポートした。

src/main/java/jp/ossc/nimbus/service/test/TestControllerService.java
テストリソースのresource、title、descriptionタグ内に、XMLコメントアウトを書けるようにした。
=> テストリソースのresource、title、descriptionタグのXMLコメントアウト対応

src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/AuthenticateInterceptorService.java, src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/AuthenticateInterceptorServiceMBean.java
マージしてください。
ログインパスとログアウトパスをそれぞれ複数指定できるようにした。
=> ログインパスとログアウトパスをそれぞれ複数指定できるようにした。

src/main/java/jp/ossc/nimbus/util/converter/DataSetServletRequestParameterConverter.java
=> multipart処理に入る条件分岐の誤り修正

src/main/java/jp/ossc/nimbus/service/test/swing/ScenarioTestView.java
=> TestSwingRunnerにTestReporterを実行する機能を追加した

src/main/java/jp/ossc/nimbus/service/test/resource/GitTestResourceManagerService.java, src/main/java/jp/ossc/nimbus/service/test/resource/GitTestResourceManagerServiceMBean.java
=> テストリソースのみをリソースとしてコピーできない不具合を修正した。

.classpath, pom.xml, src/main/java/jp/ossc/nimbus/service/test/resource/SVNTestResourceManagerService.java, src/main/java/jp/ossc/nimbus/service/test/resource/SVNTestResourceManagerServiceMBean.java
=> TestFrameworkでSVNからリソースを取得する機能を追加した

src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/AuthenticateInterceptorService.java, src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/AuthenticateInterceptorServiceMBean.java
=> AuthenticateInterceptorでログアウトした時に、セッションを無効化する機能を追加した

.settings/org.eclipse.jdt.core.prefs, src/main/java/jp/ossc/nimbus/service/ftp/ClusterFTPClientFactoryService.java, src/main/java/jp/ossc/nimbus/service/ftp/FTPErrorResponseException.java, src/main/java/jp/ossc/nimbus/service/ftp/FTPException.java, src/main/java/jp/ossc/nimbus/service/ftp/ftpclient/FTPClientFactoryService.java, src/main/java/jp/ossc/nimbus/service/ftp/ftpclient/FTPClientImpl.java, src/main/java/jp/ossc/nimbus/service/http/HttpException.java, src/main/java/jp/ossc/nimbus/service/http/HttpRequestCreateException.java, src/main/java/jp/ossc/nimbus/service/http/httpclient/HttpClientConnectTimeoutException.java, src/main/java/jp/ossc/nimbus/service/http/httpclient/HttpClientCreateTimeoutException.java, src/main/java/jp/ossc/nimbus/service/http/httpclient/HttpClientFactoryService.java, src/main/java/jp/ossc/nimbus/service/http/httpclient/HttpClientSocketTimeoutException.java, src/main/java/jp/ossc/nimbus/service/http/httpclient/HttpErrorStatusException.java, src/main/java/jp/ossc/nimbus/service/http/httpclient/HttpRequestImpl.java, src/main/java/jp/ossc/nimbus/service/http/httpclient/HttpResponseImpl.java, src/main/java/jp/ossc/nimbus/service/scp/ClusterSCPClientFactoryService.java, src/main/java/jp/ossc/nimbus/service/scp/SCPException.java, src/main/java/jp/ossc/nimbus/service/scp/ganymed/SCPClientFactoryService.java, src/main/java/jp/ossc/nimbus/service/scp/ganymed/SCPClientImpl.java, src/main/java/jp/ossc/nimbus/service/scp/jsch/SCPClientFactoryService.java, src/main/java/jp/ossc/nimbus/service/scp/jsch/SCPClientImpl.java, src/main/java/jp/ossc/nimbus/service/sftp/ClusterSFTPClientFactoryService.java, src/main/java/jp/ossc/nimbus/service/sftp/SFTPException.java, src/main/java/jp/ossc/nimbus/service/sftp/jsch/NoSuchFileSFTPException.java, src/main/java/jp/ossc/nimbus/service/sftp/jsch/SFTPClientCreateTimeoutException.java, src/main/java/jp/ossc/nimbus/service/sftp/jsch/SFTPClientFactoryService.java, src/main/java/jp/ossc/nimbus/service/sftp/jsch/SFTPClientImpl.java, src/main/java/jp/ossc/nimbus/service/test/HttpTestControllerClientService.java
=> 外部接続系のサービスで発生する例外に発生したサービス名を追加した。例外Handlerで発生サービス名を判断することが可能になる。

src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/BlockadeInterceptorService.java, src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/BlockadeInterceptorServiceMBean.java
=> HttpSession上の認証オブジェクトからSpecialUserの判断ができるように修正した

src/main/java/jp/ossc/nimbus/service/publish/udp/ConnectionFactoryFactoryService.java, src/main/java/jp/ossc/nimbus/service/publish/udp/ConnectionFactoryFactoryServiceMBean.java
=> ConnectionFactoryServiceを生成するためのFactoryServiceを作成した

src/main/java/jp/ossc/nimbus/service/publish/ClusterClientConnectionImpl.java, src/main/java/jp/ossc/nimbus/service/publish/ClusterConnectionFactoryService.java, src/main/java/jp/ossc/nimbus/service/publish/ClusterConnectionFactoryServiceMBean.java
=> 明示的にSequenceサービスを設定した場合のみ、IDに通番を付与するように改修した。

src/main/java/jp/ossc/nimbus/core/DefaultServiceLoaderConfig.java, src/main/java/jp/ossc/nimbus/core/DefaultServiceManagerService.java, src/main/java/jp/ossc/nimbus/core/IfDefMetaData.java, src/main/java/jp/ossc/nimbus/core/ManagerMetaData.java, src/main/java/jp/ossc/nimbus/core/ServerMetaData.java, src/main/java/jp/ossc/nimbus/core/ServiceLoaderConfig.java, src/main/java/jp/ossc/nimbus/core/ServiceManager.java, src/main/java/jp/ossc/nimbus/core/ServiceManagerFactory.java, src/main/java/jp/ossc/nimbus/core/Utility.java, src/main/resources/jp/ossc/nimbus/core/nimbus-service_1_0.dtd
=> ifdef要素にvalue属性を指定しない場合、name属性で指定した変数の存在だけを判定するようにした。

src/main/java/jp/ossc/nimbus/service/scheduler2/DatabaseScheduleManagerService.java
=> rowVersionをINTEGERとして扱うように修正した。

src/main/java/jp/ossc/nimbus/service/beancontrol/BeanFlowInvokerAccessImpl2.java
=> test属性や、expression要素で、@@囲みした中で、inputDef()やvar()が指定できなくなっている不具合を修正した。

src/main/java/jp/ossc/nimbus/service/publish/local/ClientConnectionImpl.java, src/main/java/jp/ossc/nimbus/service/publish/tcp/ClientConnectionImpl.java, src/main/java/jp/ossc/nimbus/service/publish/udp/ClientConnectionImpl.java
=> ClientConnectionのclose()時に、isStartReceiveをfalseにするように修正した。

src/main/java/jp/ossc/nimbus/service/keepalive/tcp/TcpKeepAliveCheckerService.java
=> setRequestBytes(byte[])で設定したバイトが使用されていない不具合を修正した

src/main/java/jp/ossc/nimbus/service/writer/log4j/FileAppenderWriterService.java
=> FileAppenderWriterServiceを使用し、出力パスのディレクトリが存在しない場合に作成するように修正した

src/main/java/jp/ossc/nimbus/service/scheduler2/AbstractSchedulerService.java, src/main/java/jp/ossc/nimbus/service/scheduler2/AbstractSchedulerServiceMBean.java
=> クラスタがjoinされていても、例外が発生しないようにした。

src/main/java/jp/ossc/nimbus/service/publish/tcp/ServerConnectionImpl.java, src/main/java/jp/ossc/nimbus/service/publish/udp/ServerConnectionImpl.java
=> close()を再帰的に呼び出した場合に、再帰呼び出しを抜けるように修正した。

src/main/java/jp/ossc/nimbus/service/test/action/HttpRequestActionService.java
=> レスポンスからInputStreamが取得できない場合に空のレスポンスファイルを作成するように修正した

src/main/java/jp/ossc/nimbus/service/jmx/DefaultMBeanServerConnectionFactoryService.java, src/main/java/jp/ossc/nimbus/service/jmx/MBeanWatcherService.java, src/main/java/jp/ossc/nimbus/service/jmx/MBeanWatcherServiceMBean.java
MBeanWatcherServiceに以下のメソッドを追加した。
・public void setMBeanServerConnectionFactoryServiceName(ServiceName
name)
・public ServiceName getMBeanServerConnectionFactoryServiceName()
=> #210のissueに対応した

src/main/java/jp/ossc/nimbus/util/converter/BeanExchangeConverter.java
setPropertyMapping()やsetPartPropertyMapping()の入力プロパティ名に"-<"を後置詞として付加すると、1対多の展開処理を行うような機能を追加した。
=> #257のissueに対応した。

src/main/java/jp/ossc/nimbus/service/writer/aws/AWSLogsWriterService.java, src/main/java/jp/ossc/nimbus/service/writer/aws/AWSLogsWriterServiceMBean.java
・CloudwatchLogsに追記できるようなロジックを追加
・isIgnoreAbortion(AbortedException時にログを書くかを判定するフラグ)をset,getできるようにする、MBeanにも記入。
・PutLogEventsReques作成をprivateのメソッドとして加筆
=> ・DescribeLogStreamsRequestで取得したLogStreamsが2つ以上の際に例外をはかせるように加筆

src/main/java/jp/ossc/nimbus/service/writer/aws/AWSLogsWriterService.java, src/main/java/jp/ossc/nimbus/service/writer/aws/AWSLogsWriterServiceMBean.java
Reverts nimbus-org/nimbus#316
不要な空白が増えている。
privateで切り出すべき処理が切り出されていない。
=> Revert "・DescribeLogStreamsRequestで取得したLogStreamsが2つ以上の際に例外をはかせるように加筆"

src/main/java/jp/ossc/nimbus/util/converter/DataSetXpathConverter.java
setDocumentBuilderClassName(String)を追加した。
マージしてください。
=> Issue #321対応

pom.xml, src/main/java/jp/ossc/nimbus/beans/dataset/DataSet.java, src/main/java/jp/ossc/nimbus/beans/dataset/QueryDataSet.java, src/main/java/jp/ossc/nimbus/beans/dataset/Record.java, src/main/java/jp/ossc/nimbus/beans/dataset/RecordList.java, src/main/java/jp/ossc/nimbus/beans/dataset/RecordSchema.java, src/main/java/jp/ossc/nimbus/core/ConstructorMetaData.java, src/main/java/jp/ossc/nimbus/core/IfDefMetaData.java, src/main/java/jp/ossc/nimbus/core/InvokeMetaData.java, src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/BlockadeCheckTargetNotFoundException.java, src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/BlockadeInterceptorService.java, src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/BlockadeInterceptorServiceMBean.java, src/main/java/jp/ossc/nimbus/service/context/SharedContextRecord.java, src/main/java/jp/ossc/nimbus/service/context/SharedContextRecordList.java, src/main/java/jp/ossc/nimbus/service/rest/BeanFlowRestServerService.java, src/main/java/jp/ossc/nimbus/service/writer/aws/AWSLogsWriterService.java, src/main/java/jp/ossc/nimbus/service/writer/aws/AWSLogsWriterServiceMBean.java, src/main/java/jp/ossc/nimbus/util/converter/DataSetHtmlConverter.java, src/main/java/jp/ossc/nimbus/util/converter/DataSetXpathConverter.java
=> Revert "・AWSLogsWriterServiceを整形、putLogEventの重複部分を取り出した。"

src/main/java/jp/ossc/nimbus/core/ArgumentMetaData.java, src/main/java/jp/ossc/nimbus/core/AttributeMetaData.java, src/main/java/jp/ossc/nimbus/core/ConstructorMetaData.java, src/main/java/jp/ossc/nimbus/core/FieldMetaData.java, src/main/java/jp/ossc/nimbus/core/InvokeMetaData.java, src/main/java/jp/ossc/nimbus/core/ObjectMetaData.java, src/main/java/jp/ossc/nimbus/core/StaticInvokeMetaData.java, src/main/java/jp/ossc/nimbus/service/rest/BeanFlowRestServerService.java, src/main/resources/jp/ossc/nimbus/service/rest/restserver_1_0.dtd
・object-def要素を追加
・request、response、object要素にref属性を追加
=> Issue #374対応

src/main/java/jp/ossc/nimbus/core/ArgumentMetaData.java, src/main/java/jp/ossc/nimbus/core/AttributeMetaData.java, src/main/java/jp/ossc/nimbus/core/ConstructorMetaData.java, src/main/java/jp/ossc/nimbus/core/FieldMetaData.java, src/main/java/jp/ossc/nimbus/core/InvokeMetaData.java, src/main/java/jp/ossc/nimbus/core/ObjectMetaData.java, src/main/java/jp/ossc/nimbus/core/StaticInvokeMetaData.java, src/main/java/jp/ossc/nimbus/service/rest/BeanFlowRestServerService.java, src/main/resources/jp/ossc/nimbus/service/rest/restserver_1_0.dtd
=> Revert "Issue #374対応"

src/main/java/jp/ossc/nimbus/service/rest/BeanFlowRestServerService.java, src/main/resources/jp/ossc/nimbus/service/rest/restserver_1_0.dtd
object-def要素に、ref属性を指定して、他のobject-def要素を継承できるようにした。
=> Issue #378対応

pom.xml, src/main/java/jp/ossc/nimbus/service/keepalive/KubernetesClusterService.java, src/main/java/jp/ossc/nimbus/service/keepalive/KubernetesClusterServiceMBean.java
=> Issue #404対応

.classpath, .gitignore, src/main/java/jp/ossc/nimbus/service/rest/BeanFlowRestServerService.java, src/main/resources/jp/ossc/nimbus/service/rest/restserver_1_0.dtd
dtdはcodeがrequiredで必須になっていたので、impliedにした。
=> #479 bug fix. refした先にcodeなくても、その先のrefまで見るようにヌルポチェックいれた。

.classpath, pom.xml, src/main/java/jp/ossc/nimbus/serverless/aws/APIGatewayRequestContext.java, src/main/java/jp/ossc/nimbus/serverless/aws/APIGatewayRequestHandler.java, src/main/java/jp/ossc/nimbus/serverless/aws/BeanFlowAPIGatewayRequestHandler.java, src/main/java/jp/ossc/nimbus/serverless/aws/BeanFlowRequestHandler.java, src/main/java/jp/ossc/nimbus/serverless/aws/BeanFlowRequestStreamHandler.java, src/main/java/jp/ossc/nimbus/serverless/aws/NimbusRequestHandler.java, src/main/java/jp/ossc/nimbus/serverless/aws/RequestContext.java, src/main/java/jp/ossc/nimbus/serverless/aws/RequestHandler.java, src/main/java/jp/ossc/nimbus/serverless/aws/RequestStreamHandler.java
AWS LambdaのRequestHandler実装を追加した
=> Issue #510対応

src/main/java/jp/ossc/nimbus/service/writer/aws/AWSLogsWriterService.java
・シーケンストークンの引継ぎロジックを修正した。
・バッファリングロジックを修正した。
=> Issue #514対応

src/main/java/jp/ossc/nimbus/core/ServiceManagerFactory.java, src/main/java/jp/ossc/nimbus/servlet/ServiceManagerFactoryServlet.java
=> Issue #574対応

src/main/java/jp/ossc/nimbus/service/context/DistributedSharedContextService.java
・再接続時にrehashされない問題を修正した。
・rehashで、増えすぎたサーバモードを減らすようにした。
=> Issue #595対応

src/main/java/jp/ossc/nimbus/service/http/proxy/HttpRequest.java, src/main/java/jp/ossc/nimbus/service/test/stub/http/HttpTestStubService.java
・スタブのHTTP要求ヘッダの大文字小文字同一視
・スタブのCORS自動応答対応
=> Issue #666対応

src/main/java/jp/ossc/nimbus/service/keepalive/ClusterService.java, src/main/java/jp/ossc/nimbus/service/keepalive/ClusterServiceMBean.java
This reverts commit 350ceb4b484a3ac526a9c4df3cfa3ab35f3650fa.
=> Revert "#695 対応 (#696)"

src/main/java/jp/ossc/nimbus/service/keepalive/ClusterService.java, src/main/java/jp/ossc/nimbus/service/keepalive/ClusterServiceMBean.java
=> Revert "#695"

pom.xml, src/main/java/jp/ossc/nimbus/beans/IndexedProperty.java, src/main/java/jp/ossc/nimbus/beans/MappedProperty.java, src/main/java/jp/ossc/nimbus/beans/SimpleProperty.java, src/main/java/jp/ossc/nimbus/service/aop/interceptor/servlet/StreamExchangeInterceptorService.java, src/main/java/jp/ossc/nimbus/service/connection/TableCreatorService.java, src/main/java/jp/ossc/nimbus/service/context/SharedContextService.java, src/main/java/jp/ossc/nimbus/service/converter/RecordListCodeMasterConverter.java, src/main/java/jp/ossc/nimbus/service/journal/editor/DataSetJSONJournalEditorService.java, src/main/java/jp/ossc/nimbus/servlet/SharedContextServlet.java, src/main/java/jp/ossc/nimbus/util/converter/BeanJSONConverter.java, src/main/java/jp/ossc/nimbus/util/converter/DataSetXMLConverter.java, src/main/java/jp/ossc/nimbus/util/converter/RecordCSVConverter.java, src/main/java/jp/ossc/nimbus/util/converter/RecordListCSVConverter.java
Issue 
https://github.com/nimbus-org/nimbus/issues/934
=> Issue #934対応
